import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {
	AiFillTwitterCircle,
	AiFillLinkedin,
	AiFillYoutube,
	AiFillInstagram,
} from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import tapin from '../public/tapin.png'
import hibye from '../public/hibye.png'
import dp from '../public/profile.png'
import bank from '../public/bank-app.png'
import { useState } from 'react'

export default function Home() {
	const [darkMode, setDarkMode] = useState(true)

	return (
		<>
			<div className={darkMode ? 'dark' : ''}>
				<Head>
					<title>Joel Portfolio</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
					<section className="min-h-screen">
						<nav className="py-10 mb-12 flex justify-between">
							<h1 className="text-xl font-burtons dark:text-white">joelak</h1>
							<ul className="flex items-center">
								<li>
									<BsFillMoonStarsFill
										onClick={() => setDarkMode(!darkMode)}
										className=" cursor-pointer text-2xl dark:text-white"
									/>
								</li>
								<li>
									<a
										className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
										href="#">
										Resume
									</a>
								</li>
							</ul>
						</nav>

						<div className="text-center p-10">
							<h2 className="text-5xl py-2 text-teal-600 font-medium">
								Joel Adu-Kwarteng
							</h2>
							<h3 className="text-xl py-2 md:text-xl text-teal-900">
								Passionate Developer | Creative Problem Solver | Lifelong
								Learner
							</h3>
							<p className="text-md py-5 leading-8 text-gray-800 md:text-lg max-w-2xl mx-auto dark:text-gray-400">
								Looking to breathe life into your digital dreams? As a
								passionate developer, I offer a symphony of services that blend
								innovation, efficiency, and elegance. From crafting captivating
								websites to building cutting-edge applications, let's embark on
								a coding adventure together and turn your ideas into
								awe-inspiring realities!
								{/* Hey there! I'm Joel. I am a web developer with a love for
								crafting innovative solutions to real-world challenges. My
								highest priority is to make your dreams come true. */}
							</p>
						</div>

						<div className="text-5xl flex justify-center gap-16 p-3 text-gray-600 dark:text-gray-400">
							<a href="https://www.linkedin.com/in/joel-adu-kwarteng-919048208/">
								<AiFillLinkedin />
							</a>
						</div>

						<div className=" bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 relative mx-auto overflow-hidden md:w-96 md:h-96">
							<Image src={dp} alt="dev ed" layout="fill" objectFit="cover" />
						</div>
					</section>

					<section>
						<div>
							<h3 className="text-3xl py-4 mt-4 text-center dark:text-teal-600">
								Services I offer
							</h3>
							<p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-400 max-w-lg mx-auto text-center">
								I create beautiful, simplistic, but most importantly, functional
								websites that meet the needs and functional requirements of the
								client. I also offer services to help improve existing websites
								and other digital platforms.
							</p>
						</div>

						<div>
							<h3 className="text-3xl py-4 mt-20 text-center text-teal-600">
								Portfolio
							</h3>
							<p className="text-lg py-2 leading-8 text-gray-400 text-center">
								Welcome to my portfolio! I am a passionate individual with a
								flair for design and problem-solving. Here, you'll find a
								diverse collection of projects, showcasing my creativity and
								technical expertise in web development and graphic design. Join
								me on this visual journey as we explore the exciting realm of
								innovation and discover how creativity can shape a brighter
								future. Thank you for visiting! 🌟
							</p>
						</div>

						<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
							<div className="basis-1/3 flex-1">
								<a href="https://whatsapp-v2-ochre.vercel.app">
									<Image
										src={hibye}
										className="rounded-xl"
										width={'100%'}
										height={'100%'}
									/>
								</a>
							</div>

							<div className="basis-1/3 flex-1">
								<a href="https://linkedin-d57df.web.app">
									<Image
										src={tapin}
										className="rounded-xl"
										width={'100%'}
										height={'100%'}
									/>
								</a>
							</div>

							<div className="basis-1/2 flex-1">
								<a href="https://github.com/Joelisking/modern-bank-app">
									<Image
										src={bank}
										className="rounded-xl"
										width={'100%'}
										height={'100%'}
									/>
								</a>
							</div>
						</div>
					</section>
				</main>
			</div>
		</>
	)
}
